src/api/urls.py
from django.conf.urls import url, patterns, include
from rest_framework.routers import DefaultRouter
from rest_framework_nested import routers
from . import views


urlpatterns = [
    url(r'^auth-devices/$', views.custom_obtain_token),
    url(r'^auth-devices/(?P<registration_id>[0-9]+)/$', views.TokenDeviceDetailAPIView.as_view()),
]

router = routers.DefaultRouter()
router.register(r'usuarios', views.UsuariosViewSet, 'usuario')
router.register(r'calendario-examenes', views.CalendarioExamenesViewSet, 'calendario-examen')
router.register(r'calendario', views.CalendarioViewSet, 'calendario')
router.register(r'calendario-temporal', views.CalendarioTemporalViewSet, 'calendario-temporal')


router.register(r'horarios-grupo', views.HorariosGrupoViewSet, 'horarios-grupo')
router.register(r'fechas-disponibles-grupo', views.FechasDisponiblesGrupoViewSet, 'fechas-disponibles-grupo')
router.register(r'fechas-inactivas', views.FechasInactivasViewSet, 'fechas-inactivas')


#usuarios_router = routers.NestedDefaultRouter(router, r'usuarios', lookup='usuario')
#usuarios_router.register(r'calendario', views.CalendarioViewSet,
#                              base_name='usuario_calendario')

urlpatterns += router.urls

src/apps/director_programa/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexDirectorProgramaView.as_view(), name='index'),
    url(r'^calendario/$', views.CalendarioDirectorProgramaView.as_view(), name='calendario'),
    url(r'^calendario-temporal/$', views.CalendarioTemporalDirectorProgramaView.as_view(), name='calendario-temporal'),
    url(r'^generar-calendario/$', views.GenerarCalendarioView.as_view(), name='programacion-calendario'),
    url(r'^generar-calendario/crear/$', views.programar_calendario, name='programar-calendario'),
    url(r'^generar-calendario/guardar/$', views.guardar_nuevo_calendario, name='guardar-calendario'),
    url(r'^generar-calendario/actualizar-examen/$', views.actualizar_programacion_valida, name='actualizar-examen-valido'),

    #url(r'^notificar/$', views.notificar, name='notificar'),

    url(r'^programacion-grupo/$', views.ProgramacionGrupoView.as_view(), name='programacion-grupo'),
    url(r'^programacion-grupo/guardar/$', views.programar_grupo_individual, name='programacion-grupo-guardar'),

    url(r'^registro-semestre/$', views.RegistroSemestre.as_view(), name='registro-semestre'),
    url(r'^registro-semestre/crear/$', views.registrar_semestre, name='registro-semestre-crear'),
    url(r'^registro-semestre/actualizar/$', views.actualizar_estado_semestre, name='registro-semestre-actualizar'),

    url(r'^registro-docente/$', views.RegistroDocente.as_view(), name='registro-docente'),
    url(r'^registro-docente/actualizar-correo/$', views.actualizar_correo_docente, name='actualizar-correo-docente'),

    url(r'^registro-grupos/$', views.RegistroDocente.as_view(), name='registro-grupos'),

    url(r'^configuracion-calendario/$', views.ConfiguracionCalendarioView.as_view(), name='configuracion-calendario'),
    url(r'^configuracion-calendario/actualizar-periodo/$', views.actualizar_periodo, name='actualizar-periodo'),

    url(r'^calendario-festivo/$', views.CalendarioFestivoView.as_view(), name='festivos'),
    url(r'^calendario-festivo/restaurar/$', views.restaurar_festivo, name='restaurar-festivos'),
    url(r'^calendario-festivo/agregar/$', views.agregar_festivo, name='agregar-festivo'),
    url(r'^calendario-festivo/actualizar/$', views.actualizar_festivo, name='actualizar-festivo'),

    url(r'^configuracion-restricciones/$', views.ConfiguracionRestriccionesView.as_view(),
        name='configuracion-restricciones'),

    url(r'^actualizacion-datos/cargar-horarios/$', views.CargarHorariosView.as_view(),
       name='cargar-horarios'),

    url(r'^ponderacion-dificultad/$', views.DificultadAsignaturasView.as_view(),
       name='ponderacion-dificultad'),

    url(r'^ver-horarios/$', views.VerHorariosView.as_view(),
       name='ver-horarios'),
]

src/schedulex/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.site.site_header = 'Schedulex Admin'
admin.site.index_title = 'Administración de la aplicación'
admin.site.site_title = 'Administrador Schedulex'
admin.site.site_url = '/login'

urlpatterns = [
    # url(r'^grappelli/', include('grappelli.urls')),
    # url(r'^jet/', include('jet.urls', 'jet')),
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v1.0/', include('api.urls', namespace='api')),

    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'^calendario/', include('apps.timetabling.urls', namespace='timetabling')),
    url(r'^estudiante/', include('apps.estudiante.urls', namespace='estudiante')),
    url(r'^docente/', include('apps.docente.urls', namespace='docente')),
    url(r'^director-programa/', include('apps.director_programa.urls', namespace='director-programa')),
    #url(r'^docente/', include('apps.timetabling.urls', namespace='timetabling')),
]

urlpatterns += staticfiles_urlpatterns()

src/apps/director_programa/models.py
from django.db import models

# Create your models here.

src/apps/director_programa/views.py
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest, JsonResponse, Http404
from django.core.exceptions import PermissionDenied
from django.views import generic
from braces import views
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.template import loader
from django.utils.decorators import method_decorator
from fcm_django.models import FCMDevice
from apps.timetabling.models import (
    ExamenCalendario,
    #ExamenTemporalCalendario,
    FechaFestivaInactiva,
    PeriodoTipoExamen,
    SemestreCalendarioAcademico,
    SemestreCalendarioPeriodoExamen
)
from api.models import (
    Materia,
    Grupo,
    Horario,
    Profesor,
)
from django.db.models import Q
from apps.timetabling.timetabling import QueriesManager
from accounts.decorators import (
    login_required_ajax,
    login_required_director_programa
)
from apps.timetabling import custom_model
from schedulex import settings
from utils.algoritmo_genetico.evol_algs import ga
from utils.notifications import send_mobile_notifications, send_email_analisis_tiempo
from utils.validators import validate_date_es
from api import serializers
from zeep import Client
from collections import OrderedDict
from operator import (
    attrgetter
)
import datetime
import json
import unidecode
import sys, traceback
import time
import pandas as pd
import numpy as np


User = get_user_model()


class IndexDirectorProgramaView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'director_programa/bienvenida_jefeplan.html'
    login_url = 'accounts:index'

    @method_decorator(login_required_director_programa())
    def get(self, request, *args, **kwargs):
        return self.render_to_response({'macromenu_actual': 'index'})


class CalendarioDirectorProgramaView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'director_programa/calendario_jefeplan.html'
    login_url = 'accounts:index'

    @method_decorator(login_required_director_programa())
    def get(self, request, *args, **kwargs):
        semestres_academicos = SemestreCalendarioAcademico.objects.all()
        try:
            semestre_academico_activo = SemestreCalendarioAcademico.objects.get(activo=True)
        except SemestreCalendarioAcademico.DoesNotExist:
            semestre_academico_activo = None
        return self.render_to_response({'macromenu_actual': 'calendario',
                                        'semestres_academicos': semestres_academicos,
                                        'semestre_academico_activo': semestre_academico_activo})


class CalendarioTemporalDirectorProgramaView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'director_programa/calendario_temporal_jefeplan.html'
    login_url = 'accounts:index'

    @method_decorator(login_required_director_programa())
    def get(self, request, *args, **kwargs):
        periodo_examen_semestre = None
        try:
            semestre_academico_activo = SemestreCalendarioAcademico.objects.get(activo=True)
            periodo_examen_semestre = SemestreCalendarioPeriodoExamen.objects.get(
                pendiente_temporal=True,
                semestre_calendario_academico=semestre_academico_activo
            )
        except SemestreCalendarioAcademico.DoesNotExist:
            semestre_academico_activo = None
        except SemestreCalendarioPeriodoExamen.DoesNotExist:
            periodo_examen_semestre = None
        return self.render_to_response({'macromenu_actual': 'calendario',
                                        'semestre_academico_activo': semestre_academico_activo,
                                        'periodo_examen_semestre': periodo_examen_semestre,})


class GenerarCalendarioView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'director_programa/generar_calendario.html'
    login_url = 'accounts:index'

    @method_decorator(login_required_director_programa())
    def get(self, request, *args, **kwargs):
        semestres_grupos = dict()
        semestres_periodos = list()
        try:
            codigos_plan = ('0' + request.user.plan_de_estudios, '1' + request.user.plan_de_estudios)
            grupos = custom_model.get_cursos_activos(plan_de_estudios=codigos_plan)
            for grupo in grupos:
                grupo_semestre = int(grupo['semestre'])
                if grupo_semestre not in semestres_grupos.keys():
                    semestres_grupos[grupo_semestre] = list()
                semestres_grupos[grupo_semestre].append(grupo)
            semestres_grupos = OrderedDict(sorted(semestres_grupos.items()))
            semestre_academico_activo = SemestreCalendarioAcademico.objects.get(activo=True)
            semestres_periodos = SemestreCalendarioPeriodoExamen.objects.filter(
                semestre_calendario_academico=semestre_academico_activo
            ).order_by('periodo_tipo_examen')
        except SemestreCalendarioAcademico.DoesNotExist:
            semestre_academico_activo = None
        return self.render_to_response(
            {'macromenu_actual': 'programacion-calendario',
             'semestres_grupos': semestres_grupos,
             'semestre_academico_activo': semestre_academico_activo,
             'semestres_periodos': semestres_periodos}
        )


class ProgramacionGrupoView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'director_programa/programacion_grupo_individual.html'
    login_url = 'accounts:index'

    @method_decorator(login_required_director_programa())
    def get(self, request, *args, **kwargs):
        semestres_calendarios_academicos = SemestreCalendarioAcademico.objects.all().order_by('-fecha_inicio')
        grupos = None
        try:
            codigos_plan = ('0' + request.user.plan_de_estudios, '1' + request.user.plan_de_estudios)
            grupos = custom_model.get_cursos_activos(plan_de_estudios=codigos_plan)
            semestre_academico_activo = SemestreCalendarioAcademico.objects.get(activo=True)
        except SemestreCalendarioAcademico.DoesNotExist:
            semestre_academico_activo = None
        return self.render_to_response({'macromenu_actual': 'programacion-calendario',
                                        'semestres_calendarios_academicos': semestres_calendarios_academicos,
                                        'grupos': grupos,
                                        'semestre_academico_activo': semestre_academico_activo,
                                        })


class RegistroSemestre(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'director_programa/registro_semestre.html'
    login_url = 'accounts:index'

    @method_decorator(login_required_director_programa())
    def get(self, request, *args, **kwargs):
        semestres_calendarios_academicos = SemestreCalendarioAcademico.objects.all().order_by('-fecha_inicio')
        semestre_academico_activo = semestres_calendarios_academicos.filter(activo=True)
        ultimo_semestre_academico = semestres_calendarios_academicos[0]
        return self.render_to_response({'macromenu_actual': 'registro-semestre',
                                        'semestres_calendarios_academicos': semestres_calendarios_academicos,
                                        'semestre_academico_activo': semestre_academico_activo,
                                        'ultimo_semestre_academico': ultimo_semestre_academico,
                                        })


class RegistroDocente(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'director_programa/registro_docente.html'
    login_url = 'accounts:index'

    @method_decorator(login_required_director_programa())
    def get(self, request, *args, **kwargs):
        profesores = Profesor.objects.all().order_by('nombres')
        return self.render_to_response({'macromenu_actual': 'registro-docente',
                                        'profesores': profesores,
                                        })


class ConfiguracionCalendarioView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'director_programa/configuracion_calendario.html'
    login_url = 'accounts:index'

    @method_decorator(login_required_director_programa())
    def get(self, request, *args, **kwargs):
        primeros_previos_semestre = None
        segundos_previos_semestre = None
        examenes_finales_semestre = None
        examenes_ho_semestre = None
        semestre_academico_activo = None
        try:
            semestre_academico_activo = SemestreCalendarioAcademico.objects.get(activo=True)
            primeros_previos_semestre = SemestreCalendarioPeriodoExamen.objects.get(
                semestre_calendario_academico=semestre_academico_activo,
                periodo_tipo_examen=PeriodoTipoExamen.objects.get(tipo_examen=1)
            )
            segundos_previos_semestre = SemestreCalendarioPeriodoExamen.objects.get(
                semestre_calendario_academico=semestre_academico_activo,
                periodo_tipo_examen=PeriodoTipoExamen.objects.get(tipo_examen=2)
            )
            examenes_finales_semestre = SemestreCalendarioPeriodoExamen.objects.get(
                semestre_calendario_academico=semestre_academico_activo,
                periodo_tipo_examen=PeriodoTipoExamen.objects.get(tipo_examen=3)
            )
            examenes_ho_semestre = SemestreCalendarioPeriodoExamen.objects.get(
                semestre_calendario_academico=semestre_academico_activo,
                periodo_tipo_examen=PeriodoTipoExamen.objects.get(tipo_examen=4)
            )
        except (SemestreCalendarioPeriodoExamen.DoesNotExist, SemestreCalendarioAcademico.DoesNotExist) as error:
            pass
        return self.render_to_response({'macromenu_actual': 'configuracion-calendario',

src/templates/director_programa/generar_calendario.html
{% extends 'base_app.html' %}
{% load static %}
{% block title%}Khronos | Generar Calendario{% endblock %}
    {% block main_header %}
        {% include 'director_programa/menu.html' %}
    {% endblock %}

    {% block content_app %}
        <h1 class="contexto--app-titulo">Programación de calendario</h1>
        <p class="contexto--app-descripcion">Esta opción le permite realizar la programación de exámenes para los
            grupos seleccionados en el período indicado. Recuerde que en el proceso se tendrán en cuenta las
            <a href="{% url 'director-programa:configuracion-restricciones' %}"
               class="link">restricciones de optimización</a> configuradas en el sistema.</p>
        <section class="section">
            <div class="list_container indicador_activo">
                <ul class="calendario_inactivos">
                    <li class="festivos-item macro_item macro_item--non_full">
                        <span class="info"><strong>Semestre activo: {% if semestre_academico_activo %}
                            {{ semestre_academico_activo.anio }} - {{ semestre_academico_activo.periodo }}
                        {% else %}El sistema no registra ningún semestre activo.{% endif %}</strong></span>
                        {% if semestre_academico_activo %}
                            <div class="icon_box">
                                <a class="fav_link icono--activo" data-fecha-festivo="2017-01-01"
                                data-estado="true">
                                    <span class="icon_container">
                                        <span class="icon icon--sm"></span>
                                    </span>
                                </a>
                            </div>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </section>
        <section class="section">
            <div class="calendar col--left">
                <div class="list_container">
                    <ul class="semestres">
                        {% for semestre, grupos in semestres_grupos.items %}
                            <li class="semestres-item macro_item macro_item--full">
                                <a id="macro_item_sublista_{{ forloop.counter0 }}" class="js-macroItem" href="#!" data-link="semestre_sublista_{{ forloop.counter0 }}"
                                data-clase-sublista=".js-sublistaGrupos">
                                    <span class="info">Semestre {{ semestre }}</span>
                                    <div class="icon_box">
                                        <span class="icon_container">
                                            <object class="icon icon--medium" type="image/svg+xml" data="{% static 'images/svg/navdown.svg' %}">
                                              <img src="" />
                                              <!-- fallback with png image for browsers with NO SVG support -->
                                            </object>
                                        </span>
                                    </div>
                                </a>
                                <ul id="semestre_sublista_{{ forloop.counter0 }}" class="sublist js-sublistaGrupos">

                                    <li class="grupo">
                                        <div class="input_group input_group--check input_group--ayuda input_group--1">
                                            <div class="check_container" style="width: 100%">
                                                <input class="checkMarcarSemestreProgramar" name="marcarSemestreProgramar" data-semestre="{{ semestre }}"
                                                   type="checkbox" class="input" style="vertical-align: text-bottom;height: 1.25rem;width: 1.25rem;" />
                                                <span><strong>Marcar/desmarcar semestre</strong></span>
                                                <span class="icon_container ayuda" data-balloon="Seleccione todos los grupos del Semestre {{ semestre }}"
                                                         data-balloon-pos="down" data-balloon-length="large">
                                                    <svg class="icon icon--sm" viewBox="0 0 309.267 309.267"
                                                         style="transform: translate(-50%, -50%);left: 50%;">
                                                        <use class="ic-1" xlink:href="#icon-question" />
                                                    </svg>
                                                </span>
                                            </div>
                                        </div>
                                    </li>

                                    {% for grupo in grupos %}
                                        <li class="grupo">
                                            <div class="input_group input_group--check input_group--1">
                                                <div class="check_container">
                                                    <input name="grupoExamenProgramar[]" type="checkbox" class="input"
                                                           value="{{ grupo.plandeestudios }}-{{ grupo.codigo }}-{{ grupo.grupo }}"
                                                    data-plan-estudios="{{ grupo.plandeestudios }}" data-codigo="{{ grupo.codigo }}"
                                                           data-literal-grupo="{{ grupo.grupo }}" data-semestre="{{ semestre }}"/>
                                                    <span>{{ grupo.plandeestudios }}{{ grupo.codigo }}-{{ grupo.grupo }} {{ grupo.nombre }}</span>
                                                </div>
                                            </div>
                                        </li>
                                    {% empty %}
                                        No hay grupos registrados.
                                    {% endfor %}
                                </ul>
                            </li>
                        {% empty %}
                            No hay grupos registrados en el sistema.
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="panel_opciones col--right">
                <form class="form form--vertical">
                    <div class="form-grupo">
                        <div class="input_group input_group--check input_group--ayuda input_group--1">
                            <a id="verCalendarioPendienteBtn" href="{% url 'director-programa:calendario-temporal' %}"
                               class="btn btn--dark" type="submit">Ver calendario pendiente</a><!--
                            --><span class="icon_container ayuda" data-balloon="A través de esta opción puede visualizar algún calendario temporal que
                                haya sido guardado sin confirmación." data-balloon-pos="down-right"
                                data-balloon-length="large">
                                <svg class="icon icon--sm" viewBox="0 0 309.267 309.267">
                                    <use class="ic-1" xlink:href="#icon-question" />
                                </svg>
                            </span>
                        </div>
                    </div>
                </form>
                <div class="input_group input_group--check input_group--ayuda input_group--1">
                    <div class="check_container">
                        <input id="checkMarcarGruposProgramar" name="marcarGruposProgramar" type="checkbox" class="input" />
                        <span>Marcar/desmarcar todos los grupos</span><!--
                        --><span class="icon_container ayuda" data-balloon="A través de esta opción puede seleccionar
                        todos los grupos del pénsum académico para programarlos." data-balloon-pos="down-right"
                            data-balloon-length="large">
                            <svg class="icon icon--sm" viewBox="0 0 309.267 309.267">
                                <use class="ic-1" xlink:href="#icon-question" />
                            </svg>
                        </span>
                    </div>
                </div>
            </div>
        </section>
        <section class="section">
            <h1 class="section-titulo">Período a programar</h1>
            <p class="descripcion">Seleccione el tipo de exámenes del semestre en curso que desee programar.</p>
            <form class="form">
                <div class="input_group input_group--check input_group--1">
                    {% for semestre_periodo in semestres_periodos %}
                        <div class="check_container">
                            <input name="periodoExamenesProgramar" type="radio" className="input"
                                   value="{{ semestre_periodo.periodo_tipo_examen.tipo_examen }}"
                                   {% if semestre_periodo.publicado %}disabled{% endif %}
                            /><span class="{% if semestre_periodo.publicado %}disabled{% endif %}">{{ semestre_periodo.periodo_tipo_examen.get_tipo_examen_display }} {% if semestre_periodo.publicado %}(calendario ya publicado){% endif %}</span>
                        </div>
                    {% empty %}
                        No hay períodos habilitados para realizar la programación.
                        Complete la <a href="{% url 'director-programa:configuracion-calendario' %}"
                                      class="link">configuración los períodos de evaluación.</a>
                    {% endfor %}
                </div>
                {% if semestres_periodos %}
                    <div class="botones">
                        <button id="programarCalendarioBtn" class="btn btn--dark" type="submit">Programar</button>
                    </div>
                {% endif %}
            </form>
        </section>
        <section class="section">
            <h1 class="section-titulo">Programación manual de exámenes</h1>
            <p class="descripcion">Como alternativa, si desea asignar la fecha de forma manual a los grupos para uno o más períodos de evaluación, puede utilizar esta
            opción.</p>
            <div class="botones">
                <a href="{% url 'director-programa:programacion-grupo' %}" class="btn btn--dark" type="submit">Programación manual de grupo</a>
            </div>
        </section>
    {% endblock %}
    {% block dialogo_cover %}
        <div id="previsualizacion_calendario_container"></div>
    {% endblock %}

    {% block scripts %}
        <script>
        /*
            new Tooltip($('#verCalendarioPendienteBtn'), {
                placement: 'top',
                title: 'A través de esta opción puede visualizar algún calendario temporal que haya sido guardado sin ' +
                'confirmación.'
            });
            */
        </script>
    {% endblock %}

src/templates/director_programa/menu.html
{% block navbar_app %}
    <nav id="navbar--app" class="navbar--app">
        <ul class="opciones_menu macromenu">
            <li class="item opciones_menu-item {% if macromenu_actual == 'index' %}active{% endif %}">
                <a href="{% url 'director-programa:index' %}">
                    <span class="icon_container">
                        <svg class="icon icon--sm"><use xlink:href="#icon-home"></use></svg>
                    </span><span class="info">Inicio</span>
                </a>
            </li>
            <li class="item opciones_menu-item {% if macromenu_actual == 'calendario' %}active{% endif %}">
                <a href="{% url 'director-programa:calendario' %}">
                    <span class="icon_container">
                        <svg class="icon icon--sm"><use xlink:href="#icon_calendar"></use></svg>
                    </span><span class="info">Calendario de Exámenes</span>
                </a>
            </li>
            <li class="item opciones_menu-item {% if macromenu_actual == 'programacion-calendario' %}active{% endif %}">
                <a href="{% url 'director-programa:programacion-calendario' %}">
                    <span class="icon_container">
                        <svg class="icon icon--sm"><use xlink:href="#icon-new-calendar"></use></svg>
                    </span><span class="info">Programar Calendario</span>
                </a>
            </li>
            <li class="item opciones_menu-item {% if macromenu_actual == 'cargar-horarios' %}active{% endif %}">
                <a href="{% url 'director-programa:cargar-horarios' %}">
                    <span class="icon_container">
                            <svg class="icon icon--sm"><use xlink:href="#icon-microsoftexcel"></use></svg>
                    </span><span class="info">Actualización de Horarios</span>
                </a>
            </li>
            <li class="item opciones_menu-item {% if macromenu_actual == 'ponderacion-dificultad' %}active{% endif %}">
                <a href="{% url 'director-programa:ponderacion-dificultad' %}">
                    <span class="icon_container">
                            <svg class="icon icon--sm"><use xlink:href="#icon-peso"></use></svg>
                    </span><span class="info">Ponderación de dificultad (asignaturas)</span>
                </a>
            </li>
            <li class="item opciones_menu-item {% if macromenu_actual == 'ver-horarios' %}active{% endif %}">
                <a href="{% url 'director-programa:ver-horarios' %}">
                    <span class="icon_container">
                            <svg class="icon icon--sm"><use xlink:href="#icon-horario"></use></svg>
                    </span><span class="info">Ver Horarios</span>
                </a>
            </li>
            <li class="item opciones_menu-item {% if macromenu_actual == 'registro-semestre' %}active{% endif %}">
                <a href="{% url 'director-programa:registro-semestre' %}">
                    <span class="icon_container">
                            <svg class="icon icon--sm"><use xlink:href="#icon-nuevo-semestre"></use></svg>
                    </span><span class="info">Registro de Semestre</span>
                </a>
            </li>
            <li class="item opciones_menu-item {% if macromenu_actual == 'configuracion-calendario' %}active{% endif %}">
                <a href="{% url 'director-programa:configuracion-calendario' %}">
                    <span class="icon_container">
                            <svg class="icon icon--sm"><use xlink:href="#icon-configuraciones"></use></svg>
                    </span><span class="info">Configuración de Semestre</span>
                </a>
            </li>
            <li class="item opciones_menu-item {% if macromenu_actual == 'registro-docente' %}active{% endif %}">
                <a href="{% url 'director-programa:registro-docente' %}">
                    <span class="icon_container">
                            <svg class="icon icon--sm"><use xlink:href="#icon-docente"></use></svg>
                    </span><span class="info">Registro Docente</span>
                </a>
            </li>

            <li class="item opciones_menu-item {% if macromenu_actual == 'festivos' %}active{% endif %}">
                <a href="{% url 'director-programa:festivos' %}">
                    <span class="icon_container">
                        <svg class="icon icon--sm"><use xlink:href="#icon-festivos"></use></svg>
                    </span><span class="info">Fechas Festivas</span>
                </a>
            </li>
            <li class="item opciones_menu-item {% if macromenu_actual == 'configuracion-restricciones' %}active{% endif %}">
                <a href="{% url 'director-programa:configuracion-restricciones' %}">
                    <span class="icon_container">
                        <svg class="icon icon--sm"><use xlink:href="#icon-lista"></use></svg>
                    </span><span class="info">Restricciones de Calendarización</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}