src/api/urls.py
from django.conf.urls import url, patterns, include
from rest_framework.routers import DefaultRouter
from rest_framework_nested import routers
from . import views


urlpatterns = [
    url(r'^auth-devices/$', views.custom_obtain_token),
    url(r'^auth-devices/(?P<registration_id>[0-9]+)/$', views.TokenDeviceDetailAPIView.as_view()),
]

router = routers.DefaultRouter()
router.register(r'usuarios', views.UsuariosViewSet, 'usuario')
router.register(r'calendario-examenes', views.CalendarioExamenesViewSet, 'calendario-examen')
router.register(r'calendario', views.CalendarioViewSet, 'calendario')
router.register(r'calendario-temporal', views.CalendarioTemporalViewSet, 'calendario-temporal')


router.register(r'horarios-grupo', views.HorariosGrupoViewSet, 'horarios-grupo')
router.register(r'fechas-disponibles-grupo', views.FechasDisponiblesGrupoViewSet, 'fechas-disponibles-grupo')
router.register(r'fechas-inactivas', views.FechasInactivasViewSet, 'fechas-inactivas')


#usuarios_router = routers.NestedDefaultRouter(router, r'usuarios', lookup='usuario')
#usuarios_router.register(r'calendario', views.CalendarioViewSet,
#                              base_name='usuario_calendario')

urlpatterns += router.urls

src/apps/docente/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexDocenteView.as_view(), name='index'),
    url(r'^cursos/$', views.CursosDocenteView.as_view(), name='cursos'),
]

src/schedulex/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.site.site_header = 'Schedulex Admin'
admin.site.index_title = 'Administración de la aplicación'
admin.site.site_title = 'Administrador Schedulex'
admin.site.site_url = '/login'

urlpatterns = [
    # url(r'^grappelli/', include('grappelli.urls')),
    # url(r'^jet/', include('jet.urls', 'jet')),
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v1.0/', include('api.urls', namespace='api')),

    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'^calendario/', include('apps.timetabling.urls', namespace='timetabling')),
    url(r'^estudiante/', include('apps.estudiante.urls', namespace='estudiante')),
    url(r'^docente/', include('apps.docente.urls', namespace='docente')),
    url(r'^director-programa/', include('apps.director_programa.urls', namespace='director-programa')),
    #url(r'^docente/', include('apps.timetabling.urls', namespace='timetabling')),
]

urlpatterns += staticfiles_urlpatterns()

src/apps/docente/models.py
from django.db import models

# Create your models here.

src/apps/docente/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.views import generic
from braces import views
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.template import loader
from fcm_django.models import FCMDevice
from apps.timetabling.models import ExamenCalendario
from apps.timetabling.timetabling import QueriesManager
from apps.timetabling import custom_model
from schedulex import settings


class IndexDocenteView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'docente/inicio_docente.html'
    login_url = 'accounts:index'

    def get(self, request, *args, **kwargs):
        return self.render_to_response({'macromenu_actual': 'index'})


class CursosDocenteView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'docente/mis_cursos.html'
    login_url = 'accounts:index'

    def get(self, request, *args, **kwargs):
        plan_estudios = self.request.GET.get('planEstudios', '115')
        cursos_matriculados = custom_model.get_cursos_profesor(
            #departamento=self.request.user.departamento,
            codigo=self.request.user.codigo,
            plan_de_estudios_matricula=plan_estudios)
        return self.render_to_response({'macromenu_actual': 'cursos',
                                        'cursos_matriculados': cursos_matriculados,
        })

src/templates/docente/inicio_docente.html
{% extends 'base_app.html' %}
{% load static %}
{% block title%}Khronos | Inicio{% endblock %}

    {% block main_header %}
        {% include 'docente/menu.html' %}
    {% endblock %}

    {% block content_app %}
        <h1 class="contexto--app-titulo">Calendario de exámenes</h1>
        <p class="contexto--app-descripcion">Visualice el calendario de sus exámenes para el semestre en curso.</p>
        <section class="section">
            <form class="form form--horizontal">
                <div class="form-grupo">
                    <div class="input_group input_group--2">
                        <label class="label" for="planEstudios">Programa Académico</label>
                        <select id="planEstudios" name="planEstudios" class="input">
                            <option value="15" selected>Ingeniería de Sistemas y Computación</option>
                            <option value="16">Ingeniería Electrónica</option>
                            <option value="19">Ingeniería Industrial</option>
                            <option value="61">Ingeniería Biotecnológica</option>
                        </select>
                    </div>
                </div>
                <button id="filtrarCalendarioDocenteBtn" class="btn btn--dark" type="submit">
                    Filtrar</button>
            </form>
        </section>
        <section class="section calendario">
            <div class="col--left">
                <div class="calendario_container box_container">
                    <div id='calendar' class="calendario"></div>
                </div>
            </div>
        </section>
    {% endblock %}

    {% block scripts %}
        <script>var cargarCalendarioVista = true;</script>
    {% endblock %}

src/templates/docente/menu.html
{% block navbar_app %}
    <nav id="navbar--app" class="navbar--app">
        <ul class="opciones_menu macromenu">
            <li class="item opciones_menu-item {% if macromenu_actual == 'index' %}active{% endif %}">
                <a href="{% url 'docente:index' %}">
                    <span class="icon_container">
                        <svg class="icon icon--sm"><use xlink:href="#icon_calendar"></use></svg>
                    </span><span class="info">Calendario Actual</span>
                </a>
            </li>
            <li class="item opciones_menu-item {% if macromenu_actual == 'cursos' %}active{% endif %}">
                <a href="{% url 'docente:cursos' %}">
                    <span class="icon_container">
                        <svg class="icon icon--sm"><use xlink:href="#icon_books"></use></svg>
                    </span><span class="info">Mis cursos</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

src/templates/docente/mis_cursos.html
{% extends 'base_app.html' %}
{% load static %}
{% block title%}Khronos | Mis cursos{% endblock %}

    {% block main_header %}
        {% include 'docente/menu.html' %}
    {% endblock %}

    {% block content_app %}
        <h1 class="contexto--app-titulo">Mis cursos</h1>
        <p class="contexto--app-descripcion">Marque como favoritas las materias de las cuales le gustaría recibir notificaciones sobre sus exámenes.</p>
        <section class="section">
            <form class="form form--horizontal" method="GET" action={% url 'docente:cursos' %}>
                <div class="form-grupo">
                    <div class="input_group input_group--2">
                        <label class="label" for="planEstudios">Programa Académico</label>
                        <select id="planEstudios" name="planEstudios" class="input">
                            <option value="115" selected>Ingeniería de Sistemas y Computación</option>
                            <option value="116">Ingeniería Electrónica</option>
                            <option value="119">Ingeniería Industrial</option>
                            <option value="161">Ingeniería Biotecnológica</option>
                        </select>
                    </div>
                </div>
                <button id="filtrarCursosDocente" class="btn btn--dark" type="submit">
                    Filtrar</button>
            </form>
        </section>
        <section class="section cursos">
            {% if cursos_matriculados %}
                <div class="list_container">
                    <ul class="lista_cursos">
                        {% for grupo in cursos_matriculados %}
                            <li class="lista_cursos-item macro_item macro_item--non_full">
                                <span class="info">{{ grupo.plandeestudios }}{{ grupo.codigo }}-{{ grupo.grupo }} {{ grupo.nombre }}</span>
                                <div class="icon_box">
                                    <a href="#!" class="fav_link">
                                        <span class="icon_container">
                                            <svg class="icon icon--medium bg_fav">
                                                <use class="ic-1" xlink:href="#icon_star_full" />
                                            </svg>
                                        </span>
                                    </a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% else %}
                <p class="">No tiene cursos matriculados para el semestre actual.</p>
            {% endif %}
            {% if cursos_list %}
                <div class="list_container">
                    <ul class="lista_cursos">
                        {% for curso in cursos_list %}
                            <li class="lista_cursos-item macro_item macro_item--non_full">
                                <span class="info">{{ curso.plandeestudios }}{{ curso.codigo }}-{{ curso.grupo }}: {{ curso.nombre }}</span>
                                <div class="icon_container">
                                    <a href="#!" class="fav_link">
                                        <span class="icon icon--medium">
                                            <svg class="icon--medium bg_fav" viewBox="0 0 309.267 309.267">
                                                <use class="ic-1" xlink:href="#icon_star_full" />
                                            </svg>
                                        </span>
                                    </a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </section>
    {% endblock %}