src/api/urls.py
from django.conf.urls import url, patterns, include
from rest_framework.routers import DefaultRouter
from rest_framework_nested import routers
from . import views


urlpatterns = [
    url(r'^auth-devices/$', views.custom_obtain_token),
    url(r'^auth-devices/(?P<registration_id>[0-9]+)/$', views.TokenDeviceDetailAPIView.as_view()),
]

router = routers.DefaultRouter()
router.register(r'usuarios', views.UsuariosViewSet, 'usuario')
router.register(r'calendario-examenes', views.CalendarioExamenesViewSet, 'calendario-examen')
router.register(r'calendario', views.CalendarioViewSet, 'calendario')
router.register(r'calendario-temporal', views.CalendarioTemporalViewSet, 'calendario-temporal')


router.register(r'horarios-grupo', views.HorariosGrupoViewSet, 'horarios-grupo')
router.register(r'fechas-disponibles-grupo', views.FechasDisponiblesGrupoViewSet, 'fechas-disponibles-grupo')
router.register(r'fechas-inactivas', views.FechasInactivasViewSet, 'fechas-inactivas')


#usuarios_router = routers.NestedDefaultRouter(router, r'usuarios', lookup='usuario')
#usuarios_router.register(r'calendario', views.CalendarioViewSet,
#                              base_name='usuario_calendario')

urlpatterns += router.urls

src/apps/estudiante/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexEstudianteView.as_view(), name='index'),
    url(r'^cursos/$', views.CursosEstudianteView.as_view(), name='cursos'),
    url(r'^notificaciones/$', views.NotificacionesEstudianteView.as_view(), name='notificaciones'),
]

src/schedulex/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.site.site_header = 'Schedulex Admin'
admin.site.index_title = 'Administración de la aplicación'
admin.site.site_title = 'Administrador Schedulex'
admin.site.site_url = '/login'

urlpatterns = [
    # url(r'^grappelli/', include('grappelli.urls')),
    # url(r'^jet/', include('jet.urls', 'jet')),
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v1.0/', include('api.urls', namespace='api')),

    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'^calendario/', include('apps.timetabling.urls', namespace='timetabling')),
    url(r'^estudiante/', include('apps.estudiante.urls', namespace='estudiante')),
    url(r'^docente/', include('apps.docente.urls', namespace='docente')),
    url(r'^director-programa/', include('apps.director_programa.urls', namespace='director-programa')),
    #url(r'^docente/', include('apps.timetabling.urls', namespace='timetabling')),
]

urlpatterns += staticfiles_urlpatterns()

src/apps/estudiante/models.py
from django.db import models

# Create your models here.

src/apps/estudiante/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.views import generic
from braces import views
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.template import loader
from fcm_django.models import FCMDevice
from apps.timetabling.models import ExamenCalendario
from apps.timetabling.timetabling import QueriesManager
from apps.timetabling import custom_model
from schedulex import settings


User = get_user_model()


class IndexEstudianteView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'estudiante/inicio_estudiante.html'
    login_url = 'accounts:index'

    def get(self, request, *args, **kwargs):
        return self.render_to_response({'macromenu_actual': 'index'})


class CursosEstudianteView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'estudiante/mis_cursos.html'
    login_url = 'accounts:index'

    def get(self, request, *args, **kwargs):
        cursos_matriculados = custom_model.get_cursos_estudiante(plan_de_estudios=request.user.plan_de_estudios,
                                                                 codigo=request.user.codigo)
        print(cursos_matriculados)
        return self.render_to_response({'macromenu_actual': 'cursos',
                                        'cursos_matriculados': cursos_matriculados,
        })


class NotificacionesEstudianteView(views.LoginRequiredMixin, generic.TemplateView):
    template_name = 'timetabling/mis_cursos.html'
    login_url = 'accounts:index'

    def get(self, request, *args, **kwargs):
        return self.render_to_response({})

src/templates/estudiante/inicio_estudiante.html
{% extends 'base_app.html' %}
{% load static %}
{% block title%}Khronos | Inicio{% endblock %}

    {% block main_header %}
        {% include 'estudiante/menu.html' %}
    {% endblock %}

    {% block content_app %}
        <h1 class="contexto--app-titulo">Calendario de exámenes</h1>
        <p class="contexto--app-descripcion">Visualice el calendario de sus exámenes para el semestre en curso.</p>
        <section class="section calendario">
            <div class="col--left">
                <div class="calendario_container box_container">
                    <div id='calendar' class="calendario"></div>
                </div>
            </div>
        </section>
    {% endblock %}

    {% block scripts %}
        <script>var cargarCalendarioVista = true;</script>
    {% endblock %}

src/templates/estudiante/menu.html
{% block navbar_app %}
    <nav id="navbar--app" class="navbar--app">
        <ul class="opciones_menu macromenu">
            <li class="item opciones_menu-item {% if macromenu_actual == 'index' %}active{% endif %}">
                <a href="{% url 'estudiante:index' %}">
                    <span class="icon_container">
                        <svg class="icon icon--sm"><use xlink:href="#icon_calendar"></use></svg>
                    </span><span class="info">Calendario Actual</span>
                </a>
            </li>
            <li class="item opciones_menu-item {% if macromenu_actual == 'cursos' %}active{% endif %}">
                <a href="{% url 'estudiante:cursos' %}">
                    <span class="icon_container">
                        <svg class="icon icon--sm"><use xlink:href="#icon_books"></use></svg>
                    </span><span class="info">Mis cursos</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

src/templates/estudiante/mis_cursos.html
{% extends 'base_app.html' %}
{% load static %}
{% block title%}Khronos | Mis cursos{% endblock %}

    {% block main_header %}
        {% include 'estudiante/menu.html' %}
    {% endblock %}

    {% block content_app %}
        <h1 class="contexto--app-titulo">Mis cursos</h1>
        <p class="contexto--app-descripcion">Marque como favoritas las materias de las cuales le gustaría recibir notificaciones sobre sus exámenes.</p>
        <section class="section cursos">
            {% if cursos_matriculados %}
                <div class="list_container">
                    <ul class="lista_cursos">
                        {% for grupo in cursos_matriculados %}
                            <li class="lista_cursos-item macro_item macro_item--non_full">
                                <span class="info">{{ grupo.plandeestudiosmatricula }}{{ grupo.materiamatricula }}-{{ grupo.grupo }} {{ grupo.nombre }}</span>
                                <div class="icon_box">
                                    <a href="#!" class="fav_link">
                                        <span class="icon_container">
                                            <svg class="icon icon--medium bg_fav">
                                                <use class="ic-1" xlink:href="#icon_star_full" />
                                            </svg>
                                        </span>
                                    </a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% else %}
                <p class="">No tiene cursos matriculados para el semestre actual.</p>
            {% endif %}
            {% if cursos_list %}
                <div class="list_container">
                    <ul class="lista_cursos">
                        {% for curso in cursos_list %}
                            <li class="lista_cursos-item macro_item macro_item--non_full">
                                <span class="info">{{ curso.plandeestudios }}{{ curso.codigo }}-{{ curso.grupo }}: {{ curso.nombre }}</span>
                                <div class="icon_container">
                                    <a href="#!" class="fav_link">
                                        <span class="icon icon--medium">
                                            <svg class="icon--medium bg_fav" viewBox="0 0 309.267 309.267">
                                                <use class="ic-1" xlink:href="#icon_star_full" />
                                            </svg>
                                        </span>
                                    </a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </section>
    {% endblock %}